version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env
    networks:
      - natapp
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - natapp

networks:
  natapp:
